name: CI-Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Python setup
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov flake8 black pygame

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pygame xvfb
